# Data Cleaning for United States Air Pollutant Emissions

The purpose of this code is the clean and prepare the air pollutant emissions dataset found on the *US Environmental Protection Agency* website. The aim is to use this data in an interactive PowerBI visualization to easily gather information on the total emissions of air pollutants in a state, per year.

## Import Packages and Dataset

In [1]:
#Import Packages
import pandas as pd
import numpy as np

In [2]:
#Import Dataset
df = pd.read_excel('/Users/guptaj/Documents/Personal Projects/PowerBi/state_tier1_caps_05Apr2023_Ktons.xlsx', sheet_name="State_Trends", header=1)
df.head()

,State FIPS,State,Tier 1 Code,Tier 1 Description,Pollutant,emissions1990,emissions1996,emissions1997,emissions1998,emissions1999,...,emissions2013,emissions2014,emissions2015,emissions2016,emissions2017,emissions2018,emissions2019,emissions2020,emissions2021,emissions2022
0,1,AL,1,Fuel Comb. Elec. Util.,CO,6.86859,8.06884,8.04705,8.12158,11.51526,...,8.327607,9.011643,8.598010,8.961460,9.352261,10.050146,8.243679,6.136744,6.136744,6.136744
1,1,AL,1,Fuel Comb. Elec. Util.,Black Carbon,NaN,NaN,NaN,NaN,NaN,...,0.201752,0.171972,0.151768,0.084038,0.111687,0.126073,0.144259,0.086327,0.086327,0.086327
2,1,AL,1,Fuel Comb. Elec. Util.,NH3,NaN,0.01516,0.01605,0.01597,0.01651,...,0.557052,0.486749,0.328625,0.310783,0.398873,0.455760,0.417551,0.551174,0.551174,0.551174
3,1,AL,1,Fuel Comb. Elec. Util.,NOX,187.79386,219.00900,209.98918,198.66722,186.38710,...,45.753625,49.710351,45.122038,28.622077,22.615421,25.706838,19.538456,13.174070,15.050143,15.302558
4,1,AL,1,Fuel Comb. Elec. Util.,Organic Carbon,NaN,NaN,NaN,NaN,NaN,...,0.411458,0.444940,0.431692,0.347358,0.562777,0.589574,0.602610,0.481718,0.481718,0.481718

Taking an initial look at the data, we can see that the states are defined by their abbreviations and their FIPS (Federal Information Processing System) codes. We can also see that there are several tiers giving the sources of each pollutant.

## Replacing State Abbreviations with Actual Names 
Here we replace the state abbreviations in the dataset with the full state names so PowerBI can easily recogize that this is a map of the United States.

In [5]:
#State Abbreviations to Full State Names
statesdict = {
            'AK': 'Alaska',
            'AL': 'Alabama',
            'AR': 'Arkansas',
            'AS': 'American Samoa',
            'AZ': 'Arizona',
            'CA': 'California',
            'CO': 'Colorado',
            'CT': 'Connecticut',
            'DC': 'District of Columbia',
            'DE': 'Delaware',
            'FL': 'Florida',
            'GA': 'Georgia',
            'GU': 'Guam',
            'HI': 'Hawaii',
            'IA': 'Iowa',
            'ID': 'Idaho',
            'IL': 'Illinois',
            'IN': 'Indiana',
            'KS': 'Kansas',
            'KY': 'Kentucky',
            'LA': 'Louisiana',
            'MA': 'Massachusetts',
            'MD': 'Maryland',
            'ME': 'Maine',
            'MI': 'Michigan',
            'MN': 'Minnesota',
            'MO': 'Missouri',
            'MP': 'Northern Mariana Islands',
            'MS': 'Mississippi',
            'MT': 'Montana',
            'NA': 'National',
            'NC': 'North Carolina',
            'ND': 'North Dakota',
            'NE': 'Nebraska',
            'NH': 'New Hampshire',
            'NJ': 'New Jersey',
            'NM': 'New Mexico',
            'NV': 'Nevada',
            'NY': 'New York',
            'OH': 'Ohio',
            'OK': 'Oklahoma',
            'OR': 'Oregon',
            'PA': 'Pennsylvania',
            'PR': 'Puerto Rico',
            'RI': 'Rhode Island',
            'SC': 'South Carolina',
            'SD': 'South Dakota',
            'TN': 'Tennessee',
            'TX': 'Texas',
            'UT': 'Utah',
            'VA': 'Virginia',
            'VI': 'Virgin Islands',
            'VT': 'Vermont',
            'WA': 'Washington',
            'WI': 'Wisconsin',
            'WV': 'West Virginia',
            'WY': 'Wyoming'
    }

In [6]:
#Replacing State Abbreviations with State Name
df['State'] = df['State'].replace(statesdict)
df.head()

,State FIPS,State,Tier 1 Code,Tier 1 Description,Pollutant,emissions1990,emissions1996,emissions1997,emissions1998,emissions1999,...,emissions2013,emissions2014,emissions2015,emissions2016,emissions2017,emissions2018,emissions2019,emissions2020,emissions2021,emissions2022
0,1,Alabama,1,Fuel Comb. Elec. Util.,CO,6.86859,8.06884,8.04705,8.12158,11.51526,...,8.327607,9.011643,8.598010,8.961460,9.352261,10.050146,8.243679,6.136744,6.136744,6.136744
1,1,Alabama,1,Fuel Comb. Elec. Util.,Black Carbon,NaN,NaN,NaN,NaN,NaN,...,0.201752,0.171972,0.151768,0.084038,0.111687,0.126073,0.144259,0.086327,0.086327,0.086327
2,1,Alabama,1,Fuel Comb. Elec. Util.,NH3,NaN,0.01516,0.01605,0.01597,0.01651,...,0.557052,0.486749,0.328625,0.310783,0.398873,0.455760,0.417551,0.551174,0.551174,0.551174
3,1,Alabama,1,Fuel Comb. Elec. Util.,NOX,187.79386,219.00900,209.98918,198.66722,186.38710,...,45.753625,49.710351,45.122038,28.622077,22.615421,25.706838,19.538456,13.174070,15.050143,15.302558
4,1,Alabama,1,Fuel Comb. Elec. Util.,Organic Carbon,NaN,NaN,NaN,NaN,NaN,...,0.411458,0.444940,0.431692,0.347358,0.562777,0.589574,0.602610,0.481718,0.481718,0.481718

## Checking for Missing Values
Here we check for any missing values in our dataset.

In [7]:
#Checking for Missing Values
df.isnull().sum()

State FIPS               0
State                   90
Tier 1 Code              0
Tier 1 Description      90
Pollutant                0
emissions1990         3210
emissions1996         2973
emissions1997         2973
emissions1998         2972
emissions1999         2855
emissions2000         2856
emissions2001         2859
emissions2002          112
emissions2003          112
emissions2004          112
emissions2005          112
emissions2006          112
emissions2007          112
emissions2008          112
emissions2009          112
emissions2010          112
emissions2011          112
emissions2012          112
emissions2013          112
emissions2014          112
emissions2015          112
emissions2016          112
emissions2017          112
emissions2018          112
emissions2019          112
emissions2020          280
emissions2021          280
emissions2022          280
dtype: int64

In the above output, we can see that generally before 2002, there is a lot of missing data. We can also see that the "State" column has 90 missing data points while the "State FIPS" column, the column that stores the FIPS codes for each state, has no missing data. We therefore use these codes to populate the state name.

In [8]:
mis_state = df[df['State'].isnull()].index.to_numpy() #Getting Indicies of all rows with a missing value in the "State" column

In [9]:
for i in mis_state:
    df.loc[i,"State"] = df.loc[i,"State FIPS"] #In places with missing value in the "State" column, save that rows' FINPS code
    tempdf = df[df['State FIPS'] == df.loc[i,"State"]] #To search for which state the FINPS corresponds to, create a dataframe with only that FINPS
    idx = tempdf.index[tempdf["State"].notna()==True] #Search for indices in the created dataframe where the "State" column is not empty
    df.loc[i,"State"] = df.loc[idx[0],"State"] #Set the originally missing "State" column value to the found state name

In [10]:
df.isnull().sum()

State FIPS               0
State                    0
Tier 1 Code              0
Tier 1 Description      90
Pollutant                0
emissions1990         3210
emissions1996         2973
emissions1997         2973
emissions1998         2972
emissions1999         2855
emissions2000         2856
emissions2001         2859
emissions2002          112
emissions2003          112
emissions2004          112
emissions2005          112
emissions2006          112
emissions2007          112
emissions2008          112
emissions2009          112
emissions2010          112
emissions2011          112
emissions2012          112
emissions2013          112
emissions2014          112
emissions2015          112
emissions2016          112
emissions2017          112
emissions2018          112
emissions2019          112
emissions2020          280
emissions2021          280
emissions2022          280
dtype: int64

We can see that we no longer have any missing state values.

## Split Data Based on Pollutant
Here we split the datasets by pollutant.

In [11]:
dfCO = df[df["Pollutant"]=="CO"]
dfBC = df[df["Pollutant"]=="Black Carbon"]
dfNH3 = df[df["Pollutant"]=="NH3"]
dfNOX = df[df["Pollutant"]=="NOX"]
dfOC = df[df["Pollutant"]=="Organic Carbon"]
dfPM10 = df[df["Pollutant"]=="PM10-PRI"]
dfPM25 = df[df["Pollutant"]=="PM25-PRI"]
dfSO2 = df[df["Pollutant"]=="SO2"]
dfVOC = df[df["Pollutant"]=="VOC"]

## Calculate the Sum of Each Pollutant Emissions Across All Tiers For Every State For Every Year
Here we calculate the sum of each pollutant emission across all Tier codes for every state, for every year.

In [12]:
states = df["State"].unique()
col1 = df.columns.get_loc("emissions1990")
col2 = df.columns.get_loc("emissions2022")

In [13]:
COsums = np.empty((54,col2-col1+1))
BCsums = np.empty((54,col2-col1+1))
NH3sums = np.empty((54,col2-col1+1))
NOXsums = np.empty((54,col2-col1+1))
OCsums = np.empty((54,col2-col1+1))
PM10sums = np.empty((54,col2-col1+1))
PM25sums = np.empty((54,col2-col1+1))
SO2sums = np.empty((54,col2-col1+1))
VOCsums = np.empty((54,col2-col1+1))

In [14]:
#Getting Sums of CO Emissions Across All Tiers For Every State for Every Year
for n in range(0,len(states)):
    tempdf = dfCO.loc[dfCO["State"]==states[n]]
    for col in range(col1,col2+1):
        COsums[n,col-col1] = tempdf.iloc[:,col].sum()

In [15]:
#Getting Sums of Black Carbon Emissions Across All Tiers For Every State for Every Year
for n in range(0,len(states)):
    tempdf = dfBC.loc[dfBC["State"]==states[n]]
    for col in range(col1,col2+1):
        BCsums[n,col-col1] = tempdf.iloc[:,col].sum()

In [16]:
#Getting Sums of NH3 Emissions Across All Tiers For Every State for Every Year
for n in range(0,len(states)):
    tempdf = dfNH3.loc[dfNH3["State"]==states[n]]
    for col in range(col1,col2+1):
        NH3sums[n,col-col1] = tempdf.iloc[:,col].sum()

In [17]:
#Getting Sums of NOX Emissions Across All Tiers For Every State for Every Year
for n in range(0,len(states)):
    tempdf = dfNOX.loc[dfNOX["State"]==states[n]]
    for col in range(col1,col2+1):
        NOXsums[n,col-col1] = tempdf.iloc[:,col].sum()

In [18]:
#Getting Sums of Organic Carbon Emissions Across All Tiers For Every State for Every Year
for n in range(0,len(states)):
    tempdf = dfOC.loc[dfOC["State"]==states[n]]
    for col in range(col1,col2+1):
        OCsums[n,col-col1] = tempdf.iloc[:,col].sum()

In [19]:
#Getting Sums of PM10-PRI Emissions Across All Tiers For Every State for Every Year
for n in range(0,len(states)):
    tempdf = dfPM10.loc[dfPM10["State"]==states[n]]
    for col in range(col1,col2+1):
        PM10sums[n,col-col1] = tempdf.iloc[:,col].sum()

In [20]:
#Getting Sums of PM25-PRI Emissions Across All Tiers For Every State for Every Year
for n in range(0,len(states)):
    tempdf = dfPM25.loc[dfPM25["State"]==states[n]]
    for col in range(col1,col2+1):
        PM25sums[n,col-col1] = tempdf.iloc[:,col].sum()

In [21]:
#Getting Sums of SO2 Emissions Across All Tiers For Every State for Every Year
for n in range(0,len(states)):
    tempdf = dfSO2.loc[dfSO2["State"]==states[n]]
    for col in range(col1,col2+1):
        SO2sums[n,col-col1] = tempdf.iloc[:,col].sum()

In [22]:
#Getting Sums of VOC Emissions Across All Tiers For Every State for Every Year
for n in range(0,len(states)):
    tempdf = dfVOC.loc[dfVOC["State"]==states[n]]
    for col in range(col1,col2+1):
        VOCsums[n,col-col1] = tempdf.iloc[:,col].sum()

## Creating Dataframes of Sums for Each Pollutant

In [23]:
#New column and row names
yrs = np.linspace(1996,2022,num=27,endpoint=True)
yrs = np.append([1990],yrs)
yrs = yrs.tolist()
states = states.tolist()

In [24]:
#CO Emission Dataframe
COsumsdf = pd.DataFrame(COsums)
COsumsdf.set_axis(yrs,axis=1,inplace=True)
COsumsdf.set_axis(states,axis=0,inplace=True)
COsumsdf.assign(Group="CO")
COsumsdf.insert(0, 'Pollutant', 'CO')
COsumsdf.replace(0, np.nan, inplace=True)

In [25]:
#Black Carbon Emission Dataframe
BCsumsdf = pd.DataFrame(BCsums)
BCsumsdf.set_axis(yrs,axis=1,inplace=True)
BCsumsdf.set_axis(states,axis=0,inplace=True)
BCsumsdf.assign(Group="Black Carbon")
BCsumsdf.insert(0, 'Pollutant', 'Black Carbon')
BCsumsdf.replace(0, np.nan, inplace=True)

In [26]:
#NH3 Emissions Dataframe
NH3sumsdf = pd.DataFrame(NH3sums)
NH3sumsdf.set_axis(yrs,axis=1,inplace=True)
NH3sumsdf.set_axis(states,axis=0,inplace=True)
NH3sumsdf.assign(Group="NH3")
NH3sumsdf.insert(0, 'Pollutant', 'NH3')
NH3sumsdf.replace(0, np.nan, inplace=True)

In [27]:
#NOX Emissions Dataframe
NOXsumsdf = pd.DataFrame(NOXsums)
NOXsumsdf.set_axis(yrs,axis=1,inplace=True)
NOXsumsdf.set_axis(states,axis=0,inplace=True)
NOXsumsdf.assign(Group="NOX")
NOXsumsdf.insert(0, 'Pollutant', 'NOX')
NOXsumsdf.replace(0, np.nan, inplace=True)

In [28]:
#Organic Carbon Emissions Dataframe
OCsumsdf = pd.DataFrame(OCsums)
OCsumsdf.set_axis(yrs,axis=1,inplace=True)
OCsumsdf.set_axis(states,axis=0,inplace=True)
OCsumsdf.assign(Group="Organic Carbon")
OCsumsdf.insert(0, 'Pollutant', 'Organic Carbon')
OCsumsdf.replace(0, np.nan, inplace=True)

In [29]:
#PM10-PRI Emissions Dataframe
PM10sumsdf = pd.DataFrame(PM10sums)
PM10sumsdf.set_axis(yrs,axis=1,inplace=True)
PM10sumsdf.set_axis(states,axis=0,inplace=True)
PM10sumsdf.assign(Group="PM10-PRI")
PM10sumsdf.insert(0, 'Pollutant', 'PM10-PRI')
PM10sumsdf.replace(0, np.nan, inplace=True)

In [30]:
#PM25-PRI Emissions Dataframe
PM25sumsdf = pd.DataFrame(PM25sums)
PM25sumsdf.set_axis(yrs,axis=1,inplace=True)
PM25sumsdf.set_axis(states,axis=0,inplace=True)
PM25sumsdf.assign(Group="PM25-PRI")
PM25sumsdf.insert(0, 'Pollutant', 'PM25-PRI')
PM25sumsdf.replace(0, np.nan, inplace=True)

In [31]:
#SO2 Emissions Dataframe
SO2sumsdf = pd.DataFrame(SO2sums)
SO2sumsdf.set_axis(yrs,axis=1,inplace=True)
SO2sumsdf.set_axis(states,axis=0,inplace=True)
SO2sumsdf.assign(Group="SO2")
SO2sumsdf.insert(0, 'Pollutant', 'SO2')
SO2sumsdf.replace(0, np.nan, inplace=True)

In [32]:
#VOC Emissions Dataframe
VOCsumsdf = pd.DataFrame(VOCsums)
VOCsumsdf.set_axis(yrs,axis=1,inplace=True)
VOCsumsdf.set_axis(states,axis=0,inplace=True)
VOCsumsdf.assign(Group="VOC")
VOCsumsdf.insert(0, 'Pollutant', 'VOC')
VOCsumsdf.replace(0, np.nan, inplace=True)

## Combining Sums Dataframes and Exporting to Excel

#### Combining Sums Dataframes: Format #1

In [33]:
sumsdf = pd.concat([COsumsdf,BCsumsdf,NH3sumsdf,NOXsumsdf,OCsumsdf,PM10sumsdf,PM25sumsdf,SO2sumsdf,VOCsumsdf])
sumsdf

,Pollutant,1990.0,1996.0,1997.0,1998.0,1999.0,2000.0,2001.0,2002.0,2003.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0
Alabama,CO,3404.01163,2440.95216,2369.26803,2361.43903,3011.541333,2265.144310,2151.200553,3051.342204,2579.090001,...,1582.059369,1598.038808,1424.043774,1343.201990,1632.789522,1581.413976,1358.029461,1277.125024,1327.410990,1300.141669
Alaska,CO,4502.12238,883.50805,2421.50089,414.61444,2113.152998,965.370474,318.280263,1253.352893,802.052227,...,958.491210,521.434184,1270.895854,3540.984844,463.599100,5269.917200,1390.918428,2489.470049,2494.931098,2491.575795
Arizona,CO,2563.04249,1876.55422,1752.07274,1794.73961,2008.201731,1942.665698,1721.562860,1765.589796,1676.183075,...,929.390137,1005.412735,934.940559,1087.345296,1231.826632,1006.057390,981.896726,1195.900488,1185.872309,1170.685258
Arkansas,CO,1706.69006,1356.08524,1326.53142,1345.25313,1293.732544,1253.756263,1232.331321,1422.920674,1432.241865,...,1077.793933,979.731190,900.678437,1282.492480,1212.747280,1177.637880,1066.212786,922.427733,940.587163,927.991861
California,CO,15255.07897,11019.29365,10062.82448,9702.05636,8208.233005,9618.345877,7787.477742,4966.199990,5425.259499,...,2857.109173,2967.534462,4053.529068,2935.341012,5244.450898,5339.156576,2192.568972,8425.077937,8437.176688,8396.284330
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wisconsin,VOC,467.13463,499.87530,497.65092,466.71969,422.310788,390.870735,389.104964,299.090262,300.429863,...,201.389090,196.079238,185.196732,199.671922,175.476590,189.401745,169.043334,215.615100,215.353984,213.502631
Wyoming,VOC,76.90427,226.74756,85.56746,79.14169,66.206221,82.159992,65.400841,175.652172,245.324511,...,145.246033,141.785960,143.013739,283.819081,175.575424,239.471148,168.289307,196.144422,196.130978,195.749401
Puerto Rico,VOC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.297415,103.204896,...,65.610164,59.819740,57.007430,50.375834,53.775493,50.423189,50.470619,42.264497,43.494409,43.307490
Virgin Islands,VOC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.997942,3.861500,...,2.386016,2.224728,2.154202,1.936838,2.020932,1.913254,1.853906,1.765826,1.782366,1.779035
TB,VOC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.998673,0.998966,...,3.278358,3.014821,3.852478,3.136427,3.107255,3.180500,3.115989,7.523611,7.523611,7.523611

In [34]:
sumsdf.to_excel('Calc_State_Emissions_Per_Year.xlsx')

#### Combining Sums Dataframes: Format #2

In [35]:
COsumsdf.index.name = 'State'
COsumsdf.reset_index(inplace=True)
COsumsdf_yrsclass = pd.melt(COsumsdf,id_vars=['State','Pollutant'],value_vars =[2022.0,2020.0,2015.0,2010.0,2005.0,2000.0])

In [36]:
BCsumsdf.index.name = 'State'
BCsumsdf.reset_index(inplace=True)
BCsumsdf_yrsclass = pd.melt(BCsumsdf,id_vars=['State','Pollutant'],value_vars =[2022.0,2020.0,2015.0,2010.0,2005.0,2000.0])

In [37]:
NH3sumsdf.index.name = 'State'
NH3sumsdf.reset_index(inplace=True)
NH3sumsdf_yrsclass = pd.melt(NH3sumsdf,id_vars=['State','Pollutant'],value_vars =[2022.0,2020.0,2015.0,2010.0,2005.0,2000.0])

In [38]:
NOXsumsdf.index.name = 'State'
NOXsumsdf.reset_index(inplace=True)
NOXsumsdf_yrsclass = pd.melt(NOXsumsdf,id_vars=['State','Pollutant'],value_vars =[2022.0,2020.0,2015.0,2010.0,2005.0,2000.0])

In [39]:
OCsumsdf.index.name = 'State'
OCsumsdf.reset_index(inplace=True)
OCsumsdf_yrsclass = pd.melt(OCsumsdf,id_vars=['State','Pollutant'],value_vars =[2022.0,2020.0,2015.0,2010.0,2005.0,2000.0])

In [40]:
PM10sumsdf.index.name = 'State'
PM10sumsdf.reset_index(inplace=True)
PM10sumsdf_yrsclass = pd.melt(PM10sumsdf,id_vars=['State','Pollutant'],value_vars =[2022.0,2020.0,2015.0,2010.0,2005.0,2000.0])

In [41]:
PM25sumsdf.index.name = 'State'
PM25sumsdf.reset_index(inplace=True)
PM25sumsdf_yrsclass = pd.melt(PM25sumsdf,id_vars=['State','Pollutant'],value_vars =[2022.0,2020.0,2015.0,2010.0,2005.0,2000.0])

In [42]:
SO2sumsdf.index.name = 'State'
SO2sumsdf.reset_index(inplace=True)
SO2sumsdf_yrsclass = pd.melt(SO2sumsdf,id_vars=['State','Pollutant'],value_vars =[2022.0,2020.0,2015.0,2010.0,2005.0,2000.0])

In [43]:
VOCsumsdf.index.name = 'State'
VOCsumsdf.reset_index(inplace=True)
VOCsumsdf_yrsclass = pd.melt(VOCsumsdf,id_vars=['State','Pollutant'],value_vars =[2022.0,2020.0,2015.0,2010.0,2005.0,2000.0])

In [44]:
sumsdf_yrsclass = pd.concat([COsumsdf_yrsclass,BCsumsdf_yrsclass,NH3sumsdf_yrsclass,NOXsumsdf_yrsclass,OCsumsdf_yrsclass,PM10sumsdf_yrsclass,PM25sumsdf_yrsclass,SO2sumsdf_yrsclass,VOCsumsdf_yrsclass])

In [45]:
sumsdf_yrsclass = sumsdf_yrsclass.rename({"variable":"Year","value":"Emissions"},axis=1)
sumsdf_yrsclass

              State Pollutant  Year    Emissions
0           Alabama        CO  2022  1300.141669
1            Alaska        CO  2022  2491.575795
2           Arizona        CO  2022  1170.685258
3          Arkansas        CO  2022   927.991861
4        California        CO  2022  8396.284330
..              ...       ...   ...          ...
319       Wisconsin       VOC  2000   390.870735
320         Wyoming       VOC  2000    82.159992
321     Puerto Rico       VOC  2000          NaN
322  Virgin Islands       VOC  2000          NaN
323              TB       VOC  2000          NaN

[2916 rows x 4 columns]

In [46]:
sumsdf_yrsclass.to_excel('Calc_State_Emissions_YearPollClass.xlsx')

## Data Resource
- US EPA,OAR. (2019, May 31). Air Pollutant Emissions Trends Data | US EPA. US EPA. https://www.epa.gov/air-emissions-inventories/air-pollutant-emissions-trends-data